# Climate Change Data — Data Cleaning

## 0. Import & Load Data

In [17]:
import pandas as pd
df = pd.read_excel('climate_change_edit.xls', engine='xlrd')

## 1. Exploratory Data Analysis

In [18]:
df.shape

(10017, 28)

In [19]:
df.head()

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0.208235,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,4.967875,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10017 entries, 0 to 10016
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country code  10017 non-null  object
 1   Country name  10017 non-null  object
 2   Series code   10017 non-null  object
 3   Series name   10017 non-null  object
 4   SCALE         10017 non-null  int64
 5   Decimals      10017 non-null  int64
 6   1990          10017 non-null  object
 7   1991          10017 non-null  object
 8   1992          10017 non-null  object
 9   1993          10017 non-null  object
 10  1994          10017 non-null  object
 11  1995          10017 non-null  object
 12  1996          10017 non-null  object
 13  1997          10017 non-null  object
 14  1998          10017 non-null  object
 15  1999          10017 non-null  object
 16  2000          10017 non-null  object
 17  2001          10017 non-null  object
 18  2002          10017 non-null  object
 19  2003          10017 non-null  object
 20  2004          10017 non-null  object
 21  2005          10017 non-null  object
 22  2006          10017 non-null  object
 23  2007          10017 non-null  object
 24  2008          10017 non-null  object
 25  2009          10017 non-null  object
 26  2010          10017 non-null  object
 27  2011          10017 non-null  object
dtypes: int64(2), object(26)
memory usage: 2.1+ MB

In [5]:
# real NaN count
df.isnull().sum()

Country code    0
Country name    0
Series code     0
Series name     0
SCALE           0
Decimals        0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
dtype: int64

In [6]:
# fake missing values encoded as '..'
(df == '..').sum()

Country code       0
Country name       0
Series code        0
Series name        0
SCALE              0
Decimals           0
1990            5163
1991            6520
1992            6364
1993            6300
1994            6238
1995            5345
1996            6213
1997            6250
1998            6199
1999            6012
2000            4521
2001            5999
2002            5960
2003            5974
2004            5792
2005            4933
2006            5781
2007            5769
2008            5414
2009            6256
2010            7685
2011            9751
dtype: int64

## 2. Data Cleaning

In [20]:
# standardize column names
df.columns = df.columns.astype(str).str.strip().str.replace(' ', '_')
print(df.columns.tolist())

['Country_code', 'Country_name', 'Series_code', 'Series_name', 'SCALE', 'Decimals', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011']

In [21]:
# replace '..' with NaN
df = df.replace('..', pd.NA)

In [22]:
# drop metadata columns
df = df.drop(columns=['SCALE', 'Decimals'])

In [10]:
# convert year columns from object to numeric
year_cols = [str(y) for y in range(1990, 2012)]
df[year_cols] = df[year_cols].apply(pd.to_numeric)
df.dtypes

Country_code     object
Country_name     object
Series_code      object
Series_name      object
1990            float64
1991            float64
1992            float64
1993            float64
1994            float64
1995            float64
1996            float64
1997            float64
1998            float64
1999            float64
2000            float64
2001            float64
2002            float64
2003            float64
2004            float64
2005            float64
2006            float64
2007            float64
2008            float64
2009            float64
2010            float64
2011            float64
dtype: object

In [11]:
# melt wide format -> long format
df_long = df.melt(
    id_vars=['Country_code', 'Country_name', 'Series_code', 'Series_name'],
    var_name='Year',
    value_name='Value'
)

df_long['Year'] = df_long['Year'].astype(int)

## 3. Validation

In [12]:
df_long.shape

(220374, 6)

In [13]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220374 entries, 0 to 220373
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Country_code  220374 non-null  object
 1   Country_name  220374 non-null  object
 2   Series_code   220374 non-null  object
 3   Series_name   220374 non-null  object
 4   Year          220374 non-null  int64
 5   Value         85935 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 10.1+ MB

In [14]:
df_long.isnull().sum()

Country_code         0
Country_name         0
Series_code          0
Series_name          0
Year                 0
Value           134439
dtype: int64

In [15]:
df_long.head()

,Country_code,Country_name,Series_code,Series_name,Year,Value
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),1990,29.574810
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),1990,0.000000
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),1990,0.000000
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),1990,0.208235
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),1990,4.967875

## 4. Save

In [16]:
df_long.to_csv('climate_change_cleaned.csv', index=False)
print('Saved: climate_change_cleaned.csv')

Saved: climate_change_cleaned.csv